apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 3
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: naveed0004/spring:9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: spring
spec:
  selector:
    app: spring 
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081

